name: Argonauts
version: 1.0
description: Bring MMORPG style classes to MC!
author: Phenom
authors: [Evan]
main: com.phenom.argonauts.Main
softdepend: [Denizen]
commands:
  isAdventurer:
    description: Check to see if a player is properly registered as an adventurer
    aliases: [adventurer, isAd]
    permission: argonauts.debug
    permission-message: You do not have permission to access Argonauts debug commands
    usage: /isAdventurer [player to check]
  check:
    description: Check the stats and other Argonauts values of an Adventurer
    aliases: [checkstats, values, val]
    permission: argonauts.debug
    permission-message: You do not have permission to access Argonauts debug commands
    usage: /check [player to check]
  isConnected:
    description: Check the database connection
    aliases: [connected, testdb, testcon]
    permission: argonauts.debug
    permission-message: You do not have permission to access Argonauts debug commands
    usage: /isConnected
  save:
    description: Save an Advneutrers current stats
    aliases: [update]
    permission: argonauts.debug
    permission-message: You do not have permission to access Argonauts debug commands
    usage: /save [player to save]